# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yleiskaava_dialog_copy_source_data_to_database.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogCopySourceDataToDatabase(object):
    def setupUi(self, DialogCopySourceDataToDatabase):
        DialogCopySourceDataToDatabase.setObjectName("DialogCopySourceDataToDatabase")
        DialogCopySourceDataToDatabase.resize(493, 384)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogCopySourceDataToDatabase.sizePolicy().hasHeightForWidth())
        DialogCopySourceDataToDatabase.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogCopySourceDataToDatabase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelSourceLayerComboBox = QtWidgets.QLabel(DialogCopySourceDataToDatabase)
        self.labelSourceLayerComboBox.setObjectName("labelSourceLayerComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSourceLayerComboBox)
        self.mMapLayerComboBoxSource = QgsMapLayerComboBox(DialogCopySourceDataToDatabase)
        self.mMapLayerComboBoxSource.setObjectName("mMapLayerComboBoxSource")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mMapLayerComboBoxSource)
        self.verticalLayout.addLayout(self.formLayout)
        self.scrollArea = QtWidgets.QScrollArea(DialogCopySourceDataToDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 466, 322))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 100))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 100))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(DialogCopySourceDataToDatabase)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(DialogCopySourceDataToDatabase)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogCopySourceDataToDatabase)
        QtCore.QMetaObject.connectSlotsByName(DialogCopySourceDataToDatabase)

    def retranslateUi(self, DialogCopySourceDataToDatabase):
        _translate = QtCore.QCoreApplication.translate
        DialogCopySourceDataToDatabase.setWindowTitle(_translate("DialogCopySourceDataToDatabase", "Kopio lähdeaineistoa tietokantaan"))
        self.labelSourceLayerComboBox.setText(_translate("DialogCopySourceDataToDatabase", "Valitse lähdekarttataso:"))
        self.label_5.setText(_translate("DialogCopySourceDataToDatabase", "TextLabel"))
        self.label.setText(_translate("DialogCopySourceDataToDatabase", "TextLabel"))
        self.label_4.setText(_translate("DialogCopySourceDataToDatabase", "TextLabel"))
        self.label_2.setText(_translate("DialogCopySourceDataToDatabase", "TextLabel"))
        self.pushButton_2.setText(_translate("DialogCopySourceDataToDatabase", "PushButton"))
        self.pushButton.setText(_translate("DialogCopySourceDataToDatabase", "PushButton"))

from qgsmaplayercombobox import QgsMapLayerComboBox
