# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yleiskaava_dialog_copy_settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogCopySettings(object):
    def setupUi(self, DialogCopySettings):
        DialogCopySettings.setObjectName("DialogCopySettings")
        DialogCopySettings.resize(400, 469)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogCopySettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(DialogCopySettings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxCreateRegulations = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxCreateRegulations.setChecked(True)
        self.checkBoxCreateRegulations.setObjectName("checkBoxCreateRegulations")
        self.verticalLayout_2.addWidget(self.checkBoxCreateRegulations)
        self.checkBoxFillLandUseClassificationWithRegulation = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxFillLandUseClassificationWithRegulation.setChecked(True)
        self.checkBoxFillLandUseClassificationWithRegulation.setObjectName("checkBoxFillLandUseClassificationWithRegulation")
        self.verticalLayout_2.addWidget(self.checkBoxFillLandUseClassificationWithRegulation)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBoxLevelOfSpatialPlan = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxLevelOfSpatialPlan.setObjectName("comboBoxLevelOfSpatialPlan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxLevelOfSpatialPlan)
        self.comboBoxSpatialPlanName = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxSpatialPlanName.setObjectName("comboBoxSpatialPlanName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxSpatialPlanName)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 358, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayoutDefaultFieldValues = QtWidgets.QGridLayout()
        self.gridLayoutDefaultFieldValues.setObjectName("gridLayoutDefaultFieldValues")
        self.verticalLayout_4.addLayout(self.gridLayoutDefaultFieldValues)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2.raise_()
        self.checkBoxCreateRegulations.raise_()
        self.groupBox_3.raise_()
        self.checkBoxFillLandUseClassificationWithRegulation.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(DialogCopySettings)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonShowCopyActions = QtWidgets.QPushButton(DialogCopySettings)
        self.pushButtonShowCopyActions.setObjectName("pushButtonShowCopyActions")
        self.horizontalLayout.addWidget(self.pushButtonShowCopyActions)
        self.pushButtonPrevious = QtWidgets.QPushButton(DialogCopySettings)
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.horizontalLayout.addWidget(self.pushButtonPrevious)
        self.pushButtonRun = QtWidgets.QPushButton(DialogCopySettings)
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.horizontalLayout.addWidget(self.pushButtonRun)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogCopySettings)
        QtCore.QMetaObject.connectSlotsByName(DialogCopySettings)

    def retranslateUi(self, DialogCopySettings):
        _translate = QtCore.QCoreApplication.translate
        DialogCopySettings.setWindowTitle(_translate("DialogCopySettings", "Kopioi lähdeaineistoa tietokantaan (vaihe 3/3)"))
        self.groupBox.setTitle(_translate("DialogCopySettings", "Kopiointiasetukset"))
        self.checkBoxCreateRegulations.setText(_translate("DialogCopySettings", "Luo tarvittaessa uudet kaavamääräykset"))
        self.checkBoxFillLandUseClassificationWithRegulation.setText(_translate("DialogCopySettings", "Täytä kaavakohteiden käyttötarkoitus kaavamääräyksen mukaan"))
        self.groupBox_2.setTitle(_translate("DialogCopySettings", "Pakolliset tiedot"))
        self.label.setText(_translate("DialogCopySettings", "Yleiskaavan nimi:"))
        self.label_2.setText(_translate("DialogCopySettings", "Kaavan taso:"))
        self.groupBox_3.setTitle(_translate("DialogCopySettings", "Oletusarvot"))
        self.label_3.setText(_translate("DialogCopySettings", "Kohdetaulu ja kenttä"))
        self.label_4.setText(_translate("DialogCopySettings", "Kohdekentän oletusarvo"))
        self.pushButtonCancel.setText(_translate("DialogCopySettings", "Peruuta"))
        self.pushButtonShowCopyActions.setText(_translate("DialogCopySettings", "Näytä ajolla tehtävät muutokset"))
        self.pushButtonPrevious.setText(_translate("DialogCopySettings", "Edellinen"))
        self.pushButtonRun.setText(_translate("DialogCopySettings", "Aja"))

